### ISSUE TITLE
StringIO: Py2 issue

### ISSUE THREAD

**Issue by tjavdar** [catch22/xournal-converters#1]

**Comment by tjavdar** [comment]
Hi,
First congrat for excellent initiative for a CL-converter!

Could not give it a try, though:
After pip install, ran:
$ xoj2pdf file.xoj                                                                                           
Traceback (most recent call last):                                                                                    
  File "/usr/bin/xoj2pdf", line 7, in <module>
    from xournal_converters.pdf import main
  File "/usr/lib/python3.6/site-packages/xournal_converters/pdf.py", line 8, in <module>
    from StringIO import StringIO
ModuleNotFoundError: No module named 'StringIO'

Seems to be a Py2->Py3 error. Do you plan a Py3-variant? Google suggests:
try:
    from StringIO import StringIO
except ImportError:
    from io import StringIO
Would this + the standard print ... -> print(...) conversion make the code Py2/Py3 neutral?

**Comment by catch22** [comment]
Hi @tjavdar, I merged a slightly updated version of your PR (see #3), and also released a new version on pypi. I just realized that we should also update setup.py to make it clear that Python 3 is supported!

Thanks for your help!
