### ISSUE TITLE
Update setup.py

### ISSUE THREAD

**Issue by catch22** [catch22/xournal-converters#4]
Right now, it says Python 2 only.

**Comment by tjavdar** [comment]
Still, it pip-installs and runs like a charm under Python 3.6.1,                                                                                                           [GCC 6.3.1 20170306], on
Linux i5 4.11.3-1-ARCH #1 SMP PREEMPT Sun May 28 10:40:17 CEST 2017 x86_64 GNU/Linux

Thanks for fast update!
/Tjavdar

PS (Not related, just  an usability hint to reduce ~20%  the size of the produced pdf):

xoj2pdf file.xoj | ps2pdfwr -dCompatibilityLevel=1.5 - file.pdf

This requires ghostscript installed, though.
/Tj.

**Comment by catch22** [comment]
Fixed in 13c2742b004172ab6e17dca4d5a473cd268f3755.
