### ISSUE TITLE
pdf annotation

### ISSUE THREAD

**Issue by VP59m** [catch22/xournal-converters#5]
Hi, I tried xournal-converters with a file.xoj of a pdf annotation, but it didn't work.
It isn't possible convert a file.xoj created by a pdf annotation?

thanks so much 
cheers Igor

**Comment by catch22** [comment]
Hi Igor, it should work when you use the `xoj2pdf` converter (but not for `xoj2html`). What's the error message?

**Comment by VP59m** [comment]
Hi, this is my terminal output:

(base) [my@desktop-MJ ~]$ xoj2pdf es.xoj
Traceback (most recent call last):
  File "/opt/anaconda/bin/xoj2pdf", line 11, in <module>
    sys.exit(main())
  File "/opt/anaconda/lib/python3.6/site-packages/xournal_converters/pdf.py", line 159, in main
    pdf_background = PdfFileReader(file(pdf_background_filename, 'rb'))
NameError: name 'file' is not defined

I installed xournal-converters in my Anaconda distribution of Python

**Comment by catch22** [comment]
Oh, I think the version on PyPI is v0.0.7 (which does not work with Python 3). Let me upload the newest version.

**Comment by catch22** [comment]
Done. Try updating to the latest version (v0.0.8)!

**Comment by VP59m** [comment]
than you so much! This is new terminal output with v0.0.8:

(base) [vp59m@desktop-MJ ~]$ xoj2pdf 181438.pdf.xoj
%PDF-1.3
Traceback (most recent call last):
  File "/opt/anaconda/bin/xoj2pdf", line 11, in <module>
    sys.exit(main())
  File "/opt/anaconda/lib/python3.6/site-packages/xournal_converters/pdf.py", line 183, in main
    pdf_writer.write(stdout)
  File "/opt/anaconda/lib/python3.6/site-packages/PyPDF2/pdf.py", line 491, in write
    object_positions.append(stream.tell())
OSError: [Errno 29] Illegal seek

**Comment by catch22** [comment]
Yuck! Could you try `xoj2pdf 181438.pdf.xoj > output.pdf` and see if the problem persists?

If so, would you mind emailing me a copy of the problematic pdf & xoj so that I can have a look?

**Comment by VP59m** [comment]
ok! Now it works! Did I wrong not to put it? 
I'm sorry and thank you so much

**Comment by catch22** [comment]
Great!

It seems like newer versions of PyPDF2 try to `seek`, but the standard output is not seekable (in contrast to when you redirect it to a file). I'll think about a way to avoid this issue.
