### ISSUE TITLE
Add proper Readme

### ISSUE THREAD

**Issue by TonyStark** [catch22/xournal-converters#6]
How to use????
Can you add more detail please?? Command, Arguments etc..
Also it cant export highlighted part from xournal file.

**Comment by catch22** [comment]
By all means do send a PR 😄

**Comment by TonyStark** [comment]
okay, i did
but what about problem on export of highlighted pdf?

**Comment by catch22** [comment]
What's the issue?

**Comment by TonyStark** [comment]
Okay the problem is ```xoj2pdf``` output doesnt render highlighted part properly

> Here is source pdf>> https://drive.google.com/open?id=1SqeiFvVfa080i7ooAbTgCeS63Ufn1BhV
> xoj file>> https://drive.google.com/open?id=1X5N5FjOqldvF_JnpfKmLMaPWD0XkwGMy
> xoj2pdf output file>> https://drive.google.com/open?id=1nP0vNpHeLP5MRhWwnDweycAF0xMkGcxV

As you seen in xoj file i added some red bullet highlight on some text part of pdf.
but after converting xoj2pdf that highlighted text disappear somehow.

**Comment by catch22** [comment]
What does it look like in the xoj file?

(You can see the highlighting as very thin red strokes after the conversion.)

**Comment by TonyStark** [comment]
bro
i posted that xoj file along with original pdf and output pdf. you can download and see....

**Comment by catch22** [comment]
I don't use xournal.

**Comment by TonyStark** [comment]
okay see this screenshot
![screenshot_2018-03-23_19-28-31](https://user-images.githubusercontent.com/5529450/37833588-94e2860a-2ea3-11e8-8970-1bea96af5f44.png)

**Comment by catch22** [comment]
I've changed the line style to match Xournal's. It should work now.
